-- CreateEnum
CREATE TYPE "UrgeStatus" AS ENUM ('PENDING', 'PEACEFUL', 'PRESENT', 'OVERCOME');

-- AlterTable
ALTER TABLE "Urge" ADD COLUMN     "status" "UrgeStatus" NOT NULL DEFAULT 'PENDING',
ALTER COLUMN "createTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateTime" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateTime" SET DEFAULT CURRENT_TIMESTAMP;
