-- AlterTable
ALTER TABLE "Urge" ALTER COLUMN "createTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createTime" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updateTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateTime" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createTime" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "updateTime" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updateTime" SET DATA TYPE TIMESTAMPTZ(6);
